{% set name = "aiostream" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiostream-{{ version }}.tar.gz
  sha256: 272aaa0d8f83beb906f5aa9022bb59046bb7a103fa3770f807c31f918595acf6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  imports:
    - aiostream
    - aiostream.stream
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vxgmichel/aiostream
  summary: Generator-based operators for asynchronous iteration
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ian-r-rose
    - shughes-uk
    - timkpaine
    - vxgmichel
