schema_version: 1

context:
  name: aiostream
  version: "0.8.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/aiostream-${{ version }}.tar.gz
  sha256: 32d180b4ab01ebb2fc59eda7fa59f496895a4d07b32fc57537d1dade2514a8a1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - typing_extensions

tests:
  - python:
      imports:
        - aiostream
        - aiostream.stream
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Generator-based operators for asynchronous iteration
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/vxgmichel/aiostream

extra:
  recipe-maintainers:
    - ian-r-rose
    - shughes-uk
    - timkpaine
    - vxgmichel
